// Auto-generated by tools/shard_bank_for_tma.py
window.TMA_BANK_META = {
  "version": "3.1.0",
  "title": "CompTIA A+ (220-1201 Core 1 & 220-1202 Core 2) Master Question Bank",
  "description": "Blueprint-aligned question bank with single, multi-select, matching, and ordering items. Scaled 100-900 scoring.",
  "passing_score_core1": 675,
  "passing_score_core2": 700,
  "max_time_minutes": 90,
  "max_questions_per_exam": 90,
  "blueprint": {
    "core1": {
      "1.0 Mobile Devices": 13,
      "2.0 Networking": 23,
      "3.0 Hardware": 25,
      "4.0 Virtualization and Cloud Computing": 11,
      "5.0 Hardware and Network Troubleshooting": 28
    },
    "core2": {
      "1.0 Operating Systems": 28,
      "2.0 Security": 28,
      "3.0 Software Troubleshooting": 23,
      "4.0 Operational Procedures": 21
    }
  },
  "shards": {
    "diagnostic_pack": {
      "path": "shards/diagnostic_pack.json",
      "count": 20,
      "size_kb": 34.1
    },
    "core1": {
      "2.0 Networking": {
        "path": "shards/core1_2_0_networking.json",
        "count": 107,
        "size_kb": 180.9
      },
      "5.0 Hardware and Network Troubleshooting": {
        "path": "shards/core1_5_0_hardware_and_network_troubleshooting.json",
        "count": 131,
        "size_kb": 245.7
      },
      "3.0 Hardware": {
        "path": "shards/core1_3_0_hardware.json",
        "count": 134,
        "size_kb": 230.8
      },
      "1.0 Mobile Devices": {
        "path": "shards/core1_1_0_mobile_devices.json",
        "count": 147,
        "size_kb": 249.7
      },
      "4.0 Virtualization and Cloud Computing": {
        "path": "shards/core1_4_0_virtualization_and_cloud_computing.json",
        "count": 117,
        "size_kb": 207.0
      }
    },
    "core2": {
      "1.0 Operating Systems": {
        "path": "shards/core2_1_0_operating_systems.json",
        "count": 130,
        "size_kb": 208.5
      },
      "3.0 Software Troubleshooting": {
        "path": "shards/core2_3_0_software_troubleshooting.json",
        "count": 138,
        "size_kb": 254.7
      },
      "4.0 Operational Procedures": {
        "path": "shards/core2_4_0_operational_procedures.json",
        "count": 95,
        "size_kb": 173.3
      },
      "2.0 Security": {
        "path": "shards/core2_2_0_security.json",
        "count": 131,
        "size_kb": 232.3
      }
    }
  }
};
