// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ClarioraSubscription
 * @notice Enterprise and individual subscription payment gateway for Clariora A+ on XDC Network.
 * @dev Accepts native XDC and XRC-20 stablecoins. Supports ISO-20022 compliant enterprise accounting references.
 */

interface IERC20 {
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

contract ClarioraSubscription {
    address public owner;
    address public treasury;

    enum Tier { NONE, PASS_24H, PRO_MONTHLY, LIFETIME }

    struct Plan {
        uint256 xdcPrice;       // Price in wei (1e18)
        uint256 xrc20Price;     // Price in token units (e.g. USDT 6 decimals or 18 decimals)
        uint256 duration;       // Duration in seconds (0 = lifetime)
        bool active;
    }

    mapping(Tier => Plan) public plans;
    mapping(address => mapping(Tier => uint256)) public userExpirations;
    mapping(bytes32 => bool) public processedOrders;

    address public xrc20Token; // Optional XRC-20 stablecoin (e.g., USDT on XDC)

    event PlanUpdated(Tier indexed tier, uint256 xdcPrice, uint256 xrc20Price, uint256 duration, bool active);
    event SubscriptionPurchased(
        address indexed user,
        Tier indexed tier,
        uint256 amountPaid,
        bool isXrc20,
        uint256 expiresAt,
        string orderId
    );
    event TreasuryUpdated(address indexed newTreasury);
    event OwnershipTransferred(address indexed oldOwner, address indexed newOwner);

    modifier onlyOwner() {
        require(msg.sender == owner, "ClarioraSubscription: caller is not owner");
        _;
    }

    constructor(address _treasury, address _xrc20Token) {
        require(_treasury != address(0), "Invalid treasury address");
        owner = msg.sender;
        treasury = _treasury;
        xrc20Token = _xrc20Token;

        // Default initial pricing on XDC Network:
        // 24-Hour Pass: 50 XDC (~$2 USD equivalent depending on market)
        plans[Tier.PASS_24H] = Plan({
            xdcPrice: 50 ether,
            xrc20Price: 2 * 1e6, // $2 USDT (6 decimals)
            duration: 1 days,
            active: true
        });

        // Pro Monthly Pass: 250 XDC (~$10 USD equivalent)
        plans[Tier.PRO_MONTHLY] = Plan({
            xdcPrice: 250 ether,
            xrc20Price: 10 * 1e6, // $10 USDT
            duration: 30 days,
            active: true
        });

        // Lifetime Master Pass: 1,200 XDC (~$50 USD equivalent)
        plans[Tier.LIFETIME] = Plan({
            xdcPrice: 1200 ether,
            xrc20Price: 50 * 1e6, // $50 USDT
            duration: 0,          // 0 represents infinite duration
            active: true
        });
    }

    /**
     * @notice Purchase a subscription tier using native XDC.
     * @param tier The subscription tier requested.
     * @param orderId Unique order reference generated by Clariora edge API.
     */
    function purchaseWithXDC(Tier tier, string calldata orderId) external payable {
        Plan memory plan = plans[tier];
        require(plan.active, "Plan is not currently active");
        require(msg.value >= plan.xdcPrice, "Insufficient XDC payment");

        bytes32 orderHash = keccak256(abi.encodePacked(orderId));
        require(!processedOrders[orderHash], "Order ID already processed");
        processedOrders[orderHash] = true;

        uint256 currentExpiry = userExpirations[msg.sender][tier];
        uint256 baseTime = currentExpiry > block.timestamp ? currentExpiry : block.timestamp;
        uint256 newExpiry = plan.duration == 0 ? type(uint256).max : baseTime + plan.duration;

        userExpirations[msg.sender][tier] = newExpiry;

        emit SubscriptionPurchased(msg.sender, tier, msg.value, false, newExpiry, orderId);

        // Forward payment directly to treasury
        (bool sent, ) = payable(treasury).call{value: plan.xdcPrice}("");
        require(sent, "Treasury transfer failed");

        // Refund any overpayment
        if (msg.value > plan.xdcPrice) {
            uint256 refund = msg.value - plan.xdcPrice;
            (bool refunded, ) = payable(msg.sender).call{value: refund}("");
            require(refunded, "Refund failed");
        }
    }

    /**
     * @notice Purchase a subscription tier using an XRC-20 stablecoin (e.g. USDT-XDC).
     */
    function purchaseWithXRC20(Tier tier, string calldata orderId) external {
        require(xrc20Token != address(0), "XRC-20 payments not enabled");
        Plan memory plan = plans[tier];
        require(plan.active, "Plan is not currently active");

        bytes32 orderHash = keccak256(abi.encodePacked(orderId));
        require(!processedOrders[orderHash], "Order ID already processed");
        processedOrders[orderHash] = true;

        uint256 currentExpiry = userExpirations[msg.sender][tier];
        uint256 baseTime = currentExpiry > block.timestamp ? currentExpiry : block.timestamp;
        uint256 newExpiry = plan.duration == 0 ? type(uint256).max : baseTime + plan.duration;

        userExpirations[msg.sender][tier] = newExpiry;

        emit SubscriptionPurchased(msg.sender, tier, plan.xrc20Price, true, newExpiry, orderId);

        bool success = IERC20(xrc20Token).transferFrom(msg.sender, treasury, plan.xrc20Price);
        require(success, "XRC-20 transfer failed");
    }

    /**
     * @notice Read remaining subscription validity for any address.
     */
    function isSubscriptionActive(address user, Tier tier) external view returns (bool active, uint256 expiresAt) {
        expiresAt = userExpirations[user][tier];
        active = (expiresAt > block.timestamp);
    }

    function setPlan(Tier tier, uint256 xdcPrice, uint256 xrc20Price, uint256 duration, bool active) external onlyOwner {
        plans[tier] = Plan(xdcPrice, xrc20Price, duration, active);
        emit PlanUpdated(tier, xdcPrice, xrc20Price, duration, active);
    }

    function setTreasury(address newTreasury) external onlyOwner {
        require(newTreasury != address(0), "Invalid treasury");
        treasury = newTreasury;
        emit TreasuryUpdated(newTreasury);
    }

    function setXrc20Token(address newToken) external onlyOwner {
        xrc20Token = newToken;
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Invalid new owner");
        address old = owner;
        owner = newOwner;
        emit OwnershipTransferred(old, newOwner);
    }
}
