#!/usr/bin/env python3
"""
Shards exam_data.json into lightweight domain and pack shards for Telegram Mini Apps (TMA).
Ensures initial mobile payload is <50KB instead of 2.1MB.
"""

import os
import json
import re

def slugify(text):
    text = re.sub(r'[^a-zA-Z0-9]+', '_', text.strip().lower())
    return text.strip('_')

def shard_bank(source_path="exam_data.json", output_dir="shards"):
    print(f"Loading {source_path}...")
    with open(source_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    meta = {
        "version": data.get("version", "3.1.0"),
        "title": data.get("title", "Clariora TMA"),
        "description": data.get("description", ""),
        "passing_score_core1": data.get("passing_score_core1", 675),
        "passing_score_core2": data.get("passing_score_core2", 700),
        "max_time_minutes": data.get("max_time_minutes", 90),
        "max_questions_per_exam": data.get("max_questions_per_exam", 90),
        "blueprint": data.get("blueprint", {}),
        "shards": {}
    }

    core1_questions = data.get("core1", [])
    core2_questions = data.get("core2", [])

    print(f"Total Core 1 questions: {len(core1_questions)}")
    print(f"Total Core 2 questions: {len(core2_questions)}")

    # 1. Create Diagnostic 20-question pack (10 from Core 1, 10 from Core 2, balanced across domains)
    diagnostic_c1 = []
    c1_by_domain = {}
    for q in core1_questions:
        d = q.get("domain", "Unknown")
        c1_by_domain.setdefault(d, []).append(q)
    for d, qlist in c1_by_domain.items():
        diagnostic_c1.extend(qlist[:2]) # 2 from each of 5 domains = 10

    diagnostic_c2 = []
    c2_by_domain = {}
    for q in core2_questions:
        d = q.get("domain", "Unknown")
        c2_by_domain.setdefault(d, []).append(q)
    for d, qlist in c2_by_domain.items():
        take = 3 if len(diagnostic_c2) < 4 else 2
        diagnostic_c2.extend(qlist[:take])
    diagnostic_pack = diagnostic_c1[:10] + diagnostic_c2[:10]

    diagnostic_path = os.path.join(output_dir, "diagnostic_pack.json")
    with open(diagnostic_path, "w", encoding="utf-8") as f:
        json.dump(diagnostic_pack, f, indent=2)
    meta["shards"]["diagnostic_pack"] = {
        "path": "shards/diagnostic_pack.json",
        "count": len(diagnostic_pack),
        "size_kb": round(os.path.getsize(diagnostic_path) / 1024, 1)
    }

    # 2. Shard Core 1 by domain
    meta["shards"]["core1"] = {}
    for domain, questions in c1_by_domain.items():
        slug = slugify(domain)
        filename = f"core1_{slug}.json"
        shard_path = os.path.join(output_dir, filename)
        with open(shard_path, "w", encoding="utf-8") as f:
            json.dump(questions, f, indent=2)
        meta["shards"]["core1"][domain] = {
            "path": f"shards/{filename}",
            "count": len(questions),
            "size_kb": round(os.path.getsize(shard_path) / 1024, 1)
        }

    # 3. Shard Core 2 by domain
    meta["shards"]["core2"] = {}
    for domain, questions in c2_by_domain.items():
        slug = slugify(domain)
        filename = f"core2_{slug}.json"
        shard_path = os.path.join(output_dir, filename)
        with open(shard_path, "w", encoding="utf-8") as f:
            json.dump(questions, f, indent=2)
        meta["shards"]["core2"][domain] = {
            "path": f"shards/{filename}",
            "count": len(questions),
            "size_kb": round(os.path.getsize(shard_path) / 1024, 1)
        }

    # 4. Save metadata index
    meta_path = os.path.join(output_dir, "meta.json")
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    # 5. Also output a JS manifest for browser inclusion without initial network call
    manifest_js_path = os.path.join(output_dir, "manifest.js")
    with open(manifest_js_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/shard_bank_for_tma.py\n")
        f.write("window.TMA_BANK_META = ")
        json.dump(meta, f, indent=2)
        f.write(";\n")

    print(f"Sharding complete! Written to {output_dir}/")
    print(f"Diagnostic pack: {len(diagnostic_pack)} questions ({meta['shards']['diagnostic_pack']['size_kb']} KB)")
    print(f"Core 1 domain shards: {len(meta['shards']['core1'])}")
    print(f"Core 2 domain shards: {len(meta['shards']['core2'])}")

if __name__ == "__main__":
    shard_bank()
